Main page
htmlacademy-htmlcss/1619703-nerds-30 pull request #2
Opened 2021-02-13 12:21 UTC by DarkenMarkin

Разметка главной

2021-02-13 21:04 UTC, maxzbest requested changes

2021-02-13 21:04 UTC, maxzbest commented on index.html
> +      <img src="https://via.placeholder.com/760x431" width="760" height="431" alt="main-image1">
Это декоративное изображение

2021-02-13 21:04 UTC, maxzbest commented on index.html
> +      <button type="button">УЗНАТЬ БОЛЬШЕ</button>
Пропущены точки индикации слайдов

2021-02-13 21:04 UTC, maxzbest commented on index.html
> +               Мир никогда не будет прежним
Текст нужно обернуть в тег `p`

2021-02-13 21:04 UTC, maxzbest commented on index.html
> +         <p><b>Мы - маленькая, но гордая
Это больше похоже на заголовок

2021-02-13 21:04 UTC, maxzbest commented on index.html
> +      <footer>
Пропущен блок с картой

2021-02-14 05:00 UTC, DarkenMarkin commented on index.html
> +      <button type="button">УЗНАТЬ БОЛЬШЕ</button>
Что-то не догоняю, плс хелп

2021-02-14 05:20 UTC, DarkenMarkin commented on index.html
> +      <button type="button">УЗНАТЬ БОЛЬШЕ</button>
Догнал

2021-02-14 11:33 UTC, merged